gems: [jekyll-paginate]
highlighter: rouge
mardown: redcloth
markdown: kramdown
title: Zhang Hansheng
permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: "/index_old/page:num"
plugins: [jekyll-paginate]
